config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_schemes
  
  resources :notices
  
  resources :covid_situations
  
  resources :covid_current
  post 'covid_current/part_locality' => 'covid_current#part_locality', :as => :part_locality
  
  #resources :covid_cases
  #get 'covid_cases/:id/confirm' => 'covid_cases#confirm', :as => :confirm_covid_case
  #get 'covid_cases/:id/pdf_confirm' => 'covid_cases#pdf_confirm', :as => :pdf_confirm_covid_case
  #get 'covid_cases/:id/pdf_suspicious' => 'covid_cases#pdf_suspicious', :as => :pdf_suspicious_covid_case
  #get 'covid_cases/:id/pdf_contact' => 'covid_cases#pdf_contact', :as => :pdf_contact_covid_case
  

  resources :localities
  resources :states
  resources :areas

  post '/get_acumulated/:locality_id/:part_date/:case_type/:new_value' => 'covid_situations#get_acumulated'

  devise_for :users
  root 'welcome#index'


end

app/models/locality.rb
class Locality < ApplicationRecord
  belongs_to :area
  has_many :covid_cases

  def to_s
  	if short_name.blank?
      name
    else 
      short_name
    end        
  end
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_locality, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /localities or /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1 or /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities or /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to locality_url(@locality), notice: "Locality was successfully created." }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1 or /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to locality_url(@locality), notice: "Locality was successfully updated." }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1 or /localities/1.json
  def destroy
    @locality.destroy

    respond_to do |format|
      format.html { redirect_to localities_url, notice: "Locality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def locality_params
      params.require(:locality).permit(:name, :postal_code, :area_id, :short_name, :enabled)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= form_with(model: locality, id: "new-locality", local: true, html: { class: "form-horizontal" }) do |form| %>
  <% if locality.errors.any? %>
    <script type="text/javascript">
      window.onload = function() {
        toastr['error']('Uno o más campos tienen errores, corrígelos y vuelve a intentarlo');
        <% locality.errors.messages.each do |key_p, message| %>
          <% key = key_p.to_s.delete_prefix(':') %>
          <% if Person.columns_hash[key].nil? %>
            <% key = key+"_id" %>
          <% end %>
          var element = document.getElementById("locality_<%= key%>");
          element.classList.add("is-invalid");
          if ("<%= message[0] %>" != ""){
            var span = document.createElement('span');
            span.className = "invalid-feedback";
            span.append("<%= message[0] %>");
            element.parentElement.append(span);
          }
        <% end %>
      }
    </script>
  <% end %>
  <div class="row">
    <div class="form-group col-md-6">

      <%= form.label :name, "Nombre de la Localidad <span style='color:red;'>*</span>".html_safe %>
      <%= form.text_field :name, :class => "form-control", :placeholder => "Rawson"  %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :postal_code, "Código Postal".html_safe %>
      <%= form.text_field :postal_code, :class => "form-control", :placeholder => "9103"  %>
    </div>

    <div class="col-md-12 form-group">
      <%= form.label :area_id, "Área Programática <span style='color:red;'>*</span>".html_safe %>
      <%= form.collection_select :area_id, Area.all, :id, :to_s, {prompt: "Seleccionar Área Programática"}, {class: "select2 select-field form-control"} %>
    </div>
    <div class="col-md-6 form-group contac-estrecho">
        <%= form.check_box :enabled, :id => "habiliatar" %>
        <%= form.label :enabled, "Habiliatar Localidad" %>
      </div>

    <div class="actions"> 
      <%= form.submit "Guardar", :class => "btn btn-primary btn-block" %>
      <%= link_to 'VER LOCALIDADES', localities_path, :class => "btn btn-secondary btn-block" %>
      <a class="btn btn-secondary btn-block mt-3" href="/">VOLVER AL INICIO</a>
    </div>

  </div>

  
<% end %>

app/views/localities/edit.html.erb
<section id="formulario" class="formulario-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2 justify-content-center">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <h2 class="text-center">Editar Localidad</h2>
              <%= render 'form', locality: @locality%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/localities/index.html.erb
<div class="container">
<col class="row">
	<h2 class="col-12 pt-2">Localidades</h2>
</col>

<table class="responsive nowrap table table-hover" id="dttb-localities" data-sort="true" data-source="<%= url_for(format: :json)%>">
  <thead>
    <tr>
      <th data-data="name">Nombre</th>
      <th data-data="postal_code">Codigo Postal</th>
      <th data-data="area">Area</th>
      <th data-data="enabled">¿Habilitada?</th>
      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px">Opciones</th>
    </tr>
  </thead>

</table>

<br>
<%= link_to 'Nueva Localidad', new_locality_path, class: "btn btn-primary", class:'btn btn-primary' %>
</div>

app/views/localities/new.html.erb
<section id="formulario" class="formulario-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="row my-2 justify-content-center">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <h2 class="text-center">Nueva Localidad</h2>
            <%= render 'form', locality: @locality %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/localities/show.html.erb
<section id="felicitaciones" class="felicitaciones-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="row justify-content-center">
                <div class="col-md-12 text-left">
                  <strong>Nombre:</strong>
                  <%= @locality.name %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Codigo Postal:</strong>
                  <%= @locality.postal_code  %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Area:</strong>
                  <%= @locality.area %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>¿Habilitada?:</strong>
                  <%= @locality.enabled  %>
                </div>

                <div class="actions col-md-12 text-left"> 
                    <%= link_to 'EDITAR LOCALIDADES', edit_locality_path(@locality), :class => "btn btn-primary btn-block" %>
                    <%= link_to 'VER LOCALIDADES', localities_path, :class => "btn btn-secondary btn-block" %>
                    <a class="btn btn-secondary btn-block mt-3" href="/">VOLVER AL INICIO</a>
                </div>
            
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>