config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_schemes
  
  resources :notices
  
  resources :covid_situations
  
  resources :covid_current
  post 'covid_current/part_locality' => 'covid_current#part_locality', :as => :part_locality
  
  #resources :covid_cases
  #get 'covid_cases/:id/confirm' => 'covid_cases#confirm', :as => :confirm_covid_case
  #get 'covid_cases/:id/pdf_confirm' => 'covid_cases#pdf_confirm', :as => :pdf_confirm_covid_case
  #get 'covid_cases/:id/pdf_suspicious' => 'covid_cases#pdf_suspicious', :as => :pdf_suspicious_covid_case
  #get 'covid_cases/:id/pdf_contact' => 'covid_cases#pdf_contact', :as => :pdf_contact_covid_case
  

  resources :localities
  resources :states
  resources :areas

  post '/get_acumulated/:locality_id/:part_date/:case_type/:new_value' => 'covid_situations#get_acumulated'

  devise_for :users
  root 'welcome#index'


end

app/models/notice.rb
class Notice < ApplicationRecord
  has_one_attached :image

  validates :titulo, presence: true
  validates :cuerpo, presence: true
  validates :tipo, presence: true
  validates :fecha, presence: true
  
  validate :image_validator

  private
    def image_validator
      if image.attached?
        if !image.content_type.in?(%w(image/png image/jpeg))
           errors.add(:image, 'must be an image')
        end
      end
    end 


end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController

  require 'chronic'
  before_action :authenticate_user!, :only => [:edit]
  before_action :set_notice, only: %i[ show edit update destroy ]
  load_and_authorize_resource


  # GET /notices or /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1 or /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices or /notices.json
  def create
    respond_to do |format|
      if @notice.save
        format.html { redirect_to notice_url(@notice), notice: "Noticia creada correctamente." }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1 or /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to notice_url(@notice), notice: "Noticia actualizada correctamente." }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1 or /notices/1.json
  def destroy
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url, notice: "Noticia eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:titulo, :subtitulo, :cuerpo, :image, :tipo, :fecha)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true) do |form| %>
  
  <% if notice.errors.any? %>

      <script type="text/javascript">
        window.onload = function() {
          toastr['error']('Uno o más campos tienen errores, corrígelos y vuelve a intentarlo');
          <% notice.errors.messages.each do |key_p, message| %>

            <% key = key_p.to_s.delete_prefix(':') %>
            <% if Notice.columns_hash[key].nil? %>
              <% key = key+"_id" %>
            <% end %>
            var element = document.getElementById("notice_<%= key%>");
            element.classList.add("is-invalid");
            if ("<%= message[0] %>" != ""){
              var span = document.createElement('span');
              span.className = "invalid-feedback";
              span.append("<%= message[0] %>");
              element.parentElement.append(span);
            }
          <% end %>
        }
      </script>
  <% end %>
  <div class="row">
    <div class="form-group col-md-6">
        <%= form.label :tipo, "Tipo de noticia".html_safe %>
        <%= form.select :tipo, ["Programas de Salud","Vacunación","Coronavirus","Infraestructura Sanitaria","Maternidad,Infancia y Adolescencia","Epidemiología","Hospitales","Agenda Oficial","Promoción y Prevención","General"], {prompt: "Seleccionar"}, {class: "select2 custom-select"} %>
    </div>

     <div class="form-group col-md-6">
        <%= form.label :fecha, "Fecha de la noticia".html_safe %>
        <%= form.text_field :fecha, hide_label:true, :class => "datepicker form-control"%>
      </div>
     
   
    <div class="form-group col-md-6">
        <%= form.label :titulo, "Título <span style='color:red;'>*</span>".html_safe %>
        <%= form.text_field :titulo, :class => "form-control"  %>
     </div>
    <div class="form-group col-md-6">
        <%= form.label :subtitulo, "Subtítulo <span style='color:red;'>*</span>".html_safe %>
        <%= form.text_field :subtitulo, :class => "form-control" %>
     </div>

    <div class="form-group col-md-12">
        <%= form.label :cuerpo, "Cuerpo de la noticia <span style='color:red;'>*</span>".html_safe %>
        <%= form.text_area :cuerpo, :class => "form-control" %>
     </div>

    <div class="form-group col-md-12">
      <div class="alert alert-warning" role="alert">
        La imagen a adjuntar debe tener extencion jpg, jpeg o png.
      </div>
      <%= form.label :image, "Imagen <span style='color:red;'>*</span>".html_safe %>
      <%= form.file_field :image %>
    </div>
    <div class="actions col-md-12">
      <%= form.submit :class => "btn btn-primary"%>
      <%= link_to 'Volver', notices_path, :class => "btn btn-secondary" %>
    </div>
 
  </div>

<% end %>

app/views/notices/edit.html.erb
<section id="formulario" class="formulario-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2 justify-content-center">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <h2 class="text-center">Editar Noticia</h2>
              <%= render 'form', notice: @notice %> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/notices/index.html.erb
<div class="container">
	<col class="row">
	<h2 class="col-12 pt-2"><%= fa_icon "newspaper-o" %> Portal de Noticias</h2>
	</col>
	<% if (!@current_user.nil? and @current_user.communication?) %>
	<div class="col-12">
  <table class="responsive nowrap table table-hover " id="dttb-notices" data-sort="true" data-source="<%= url_for(format: :json)%>">
	  <thead>
	    <tr>
	      <th data-data="fecha">Fecha</th>
	      <th data-data="titulo">Titulo</th>
	      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px">Opciones</th>
	    </tr>
	  </thead>

	</table>
	<br>
	<%= link_to 'Cargar Noticia', new_notice_path, class: "btn btn-primary", class:'btn btn-primary' %>
	</div>
	<%end%>

	<% if (!Notice.count.zero?) && (Notice.count >= 3) %>

		<div class="top-section col-12 mt-5">
			<div class="row featured-4 mb-5">
				<div class="col-md-7 pe-md-5">
					<div class="card card-full text-light overflow zoom">
						<div class="height-ratio image-wrapper">
						
						<%=image_tag(url_for(@notices[0].image),:class => "notice-image img-fluid mx-auto", :style => "width: 720px; min-height: 507px; object-fit:cover; object-position:center;", :sizes => "(max-width: 720px) 100vw, 720px")%>
						</div>
						<div class="position-absolute p-3 b-0 w-100 bg-lg-shadow">
							<!-- post title -->
						 	<h2 class="h3 h2-sm h1-md display-4-lg fw-bold heading-letter-spacing text-white"><%=link_to @notices[0].titulo, @notices[0], :class=> "text-white"%></h2>
							<!-- date -->
							<div class="news-meta mb-2">
								<span class="white fw-bold"><%@notices[0].fecha%></span>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-5">
	        <!-- Trending Top -->
	        <div class="row">
	          <div class="col-lg-12 col-md-6 col-sm-6 mb-3">
	            <div class="card card-full text-light overflow zoom">
								<div class="height-ratio image-wrapper">
								
								<%=image_tag(url_for(@notices[1].image),:class => "notice-image img-fluid mx-auto", :style => "width: 510px; min-height: 200px; object-fit:cover; object-position:center;", :sizes => "(max-width: 510px) 100vw, 510px")%>
								</div>
								<div class="position-absolute p-3 b-0 w-100 bg-lg-shadow">
									<!-- post title -->
								 	<h2 class="h3 h2-sm h1-md display-4-lg fw-bold heading-letter-spacing text-white"><%=link_to @notices[1].titulo, @notices[1], :class=> "text-white"%></h2>
									<!-- date -->
									<div class="news-meta mb-2">
										<span class="white fw-bold"><%@notices[1].fecha%></span>
									</div>
								</div>
							</div>
	          </div>
	          <div class="col-lg-12 col-md-6 col-sm-6">
	            <div class="card card-full text-light overflow zoom">
								<div class="height-ratio image-wrapper">
								
								<%=image_tag(url_for(@notices[2].image),:class => "notice-image img-fluid mx-auto", :style => "width: 510px; min-height: 200px; object-fit:cover; object-position:center;", :sizes => "(max-width: 510px) 100vw, 510px")%>
								</div>
								<div class="position-absolute p-3 b-0 w-100 bg-lg-shadow">
									<!-- post title -->
								 	<h2 class="h3 h2-sm h1-md display-4-lg fw-bold heading-letter-spacing text-white"><%=link_to @notices[2].titulo, @notices[2], :class=> "text-white"%></h2>
									<!-- date -->
									<div class="news-meta mb-2">
										<span class="white fw-bold"><%@notices[2].fecha%></span>
									</div>
								</div>
							</div>
	          </div>
	        </div>
	      </div>
			</div>
		</div>
	<% end %>	
</div>

app/views/notices/new.html.erb
<section id="formulario" class="formulario-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="row my-2 justify-content-center">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <h2 class="text-center">Nueva Noticia</h2>
            <%= render 'form', notice: @notice %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/notices/show.html.erb
<section id="felicitaciones" class="felicitaciones-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="row justify-content-center">
               <%if @notice.image.attached?%>
                  <div class="col-md-4 text-left">
                      <%=image_tag(url_for(@notice.image),:class => "notice-image img-fluid mx-auto",:style => "width: 500px; min-height: 400px; height:400px; object-fit:none; object-position:center;")%>
                  </div>
                  <div class="col-md-8 text-left">
                <%else%>
                  <div class="col-md-12 text-left">
                <%end%>  
             	    <div class="lead font-weight-bold font-italic text-muted"><%= @notice.tipo %> </div>
                  <div class="lead font-weight-bold font-italic"><%= @notice.fecha.strftime('%d/%m/%Y')%></div>
                  <h2> <%= @notice.titulo %>.</h2>
                  <h3 class="notice-heading text-muted font-italic"><%= @notice.subtitulo %></h3>
                  <hr>
                  <%= @notice.cuerpo %>
  				      </div>
              </div>                
              <div class="row">
                <% if can? :update, @notice %>
                <div class="col-md-4">
                  <%= link_to 'EDITAR NOTICIA', edit_notice_path(@notice), class:"btn btn-primary btn-block mt-3" %> 
                </div>
                <div class="col-md-4">
					        <%= link_to 'VOLVER A NOTICIAS', notices_path, class:"btn btn-secondary btn-block mt-3" %>
			      	  </div>
                <%end%>
				        <div class="col-md-4">
					        <a class="btn btn-secondary btn-block mt-3" href="/">VOLVER AL INICIO</a>
				        </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>