config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_schemes
  
  resources :notices
  
  resources :covid_situations
  
  resources :covid_current
  post 'covid_current/part_locality' => 'covid_current#part_locality', :as => :part_locality
  
  #resources :covid_cases
  #get 'covid_cases/:id/confirm' => 'covid_cases#confirm', :as => :confirm_covid_case
  #get 'covid_cases/:id/pdf_confirm' => 'covid_cases#pdf_confirm', :as => :pdf_confirm_covid_case
  #get 'covid_cases/:id/pdf_suspicious' => 'covid_cases#pdf_suspicious', :as => :pdf_suspicious_covid_case
  #get 'covid_cases/:id/pdf_contact' => 'covid_cases#pdf_contact', :as => :pdf_contact_covid_case
  

  resources :localities
  resources :states
  resources :areas

  post '/get_acumulated/:locality_id/:part_date/:case_type/:new_value' => 'covid_situations#get_acumulated'

  devise_for :users
  root 'welcome#index'


end

app/models/covid_situation.rb
class CovidSituation < ApplicationRecord
  	belongs_to :locality
  
	validates :locality, presence: true
	validates :part_date, presence: true
	validates :ambulatory, presence: true
	validates :general_room, presence: true
	validates :uti_with_arm, presence: true
	validates :uti_without_arm, presence: true
	validates :new_recovered, presence: true
	validates :new_cases, presence: true
	validates :new_deceased, presence: true

	validates_uniqueness_of :locality, scope: :part_date

	def acumulated_new(fecha=part_date)
		return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:new_cases)
	end

	def acumulated_recovered(fecha=part_date)
		return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:new_recovered)
	end

	def acumulated_deceased(fecha=part_date)
		return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:new_deceased)
	end

	def acumulated_actives (fecha=part_date)
		return acumulated_new(fecha) - acumulated_recovered(fecha) - acumulated_deceased(fecha)
	end
	
	# def acumulated_ambulatory (fecha=part_date)
	# 	return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:ambulatory)
	# end

	# def acumulated_general_room (fecha=part_date)
	# 	return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:general_room)
	# end
	
	# def acumulated_uti_with_arm (fecha=part_date)
	# 	return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:uti_with_arm)
	# end

	# def acumulated_uti_without_arm (fecha=part_date)
	# 	return CovidSituation.where(locality: locality).where('part_date <=?', fecha).sum(:uti_without_arm)
	# end

end

app/controllers/covid_situations_controller.rb
class CovidSituationsController < ApplicationController

  require 'chronic'
  before_action :authenticate_user!
  before_action :set_covid_situation, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /covid_situations or /covid_situations.json
  def index
    @covid_situations = CovidSituation.all
  end

  # GET /covid_situations/1 or /covid_situations/1.json
  def show
  end

  # GET /covid_situations/new
  def new
    @covid_situation = CovidSituation.new
  end

  # GET /covid_situations/1/edit
  def edit
    @localidades = Locality.where(area: Area.where(abbreviation: current_user.area).first)
  end

  # POST /get_acumulated/locality/date_part/new_cases/10
  def get_acumulated
    locality = Locality.find(params[:locality_id])
    part_date = params[:part_date].to_date
    case_type = params[:case_type]
    new_value = params[:new_value]
    
    case case_type
    when "new_cases"
      value = CovidSituation.where(locality: locality).where('part_date <=?', part_date).sum(:new_cases) + new_value.to_i
    when "new_recovered"
      value = CovidSituation.where(locality: locality).where('part_date <=?', part_date).sum(:new_recovered) + new_value.to_i      
    when "new_deceased"
      value = CovidSituation.where(locality: locality).where('part_date <=?', part_date).sum(:new_deceased) + new_value.to_i      
    end

    respond_to do |format|
      format.json  { render :json => {:function => "get_acumulated", :case_type => case_type, :value => value}}
    end
  end  

  # POST /covid_situations or /covid_situations.json
  def create
    @covid_situation = CovidSituation.new(covid_situation_params)
    respond_to do |format|
      if @covid_situation.save
        flash[:notice] = 'La situación de la localidad se creó correctamente.'
        format.html { render action: "index"}
        format.json { render :show, status: :created, location: @covid_situation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @covid_situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /covid_situations/1 or /covid_situations/1.json
  def update
    respond_to do |format|
      if @covid_situation.update(covid_situation_params)
        format.html { redirect_to covid_situation_url(@covid_situation), notice: 'La situación de la localidad se actualizó correctamente.' }
        @covid_situations = CovidSituation.all    
        format.json { render :show, status: :ok, location: @covid_situation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @covid_situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covid_situations/1 or /covid_situations/1.json
  def destroy
    @covid_situation.destroy

    respond_to do |format|
      format.html { redirect_to covid_situations_url, notice: "Covid situation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_covid_situation
      @covid_situation = CovidSituation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def covid_situation_params
      params.require(:covid_situation).permit(:locality_id, :part_date, :ambulatory, :general_room, :uti_with_arm, :uti_without_arm, :new_cases, :new_recovered, :new_deceased)
    end
end

app/helpers/covid_situations_helper.rb
module CovidSituationsHelper
end

app/views/covid_situations/_form.html.erb
<%= form_with(model: covid_situation, local: true) do |form| %>
  <% if covid_situation.errors.any? %>
    <script type="text/javascript">
      window.onload = function() {
        toastr['error']('Uno o más campos tienen errores, corrígelos y vuelve a intentarlo');
        <% covid_situation.errors.messages.each do |key_p, message| %>

          <% key = key_p.to_s.delete_prefix(':') %>
          <% if CovidSituation.columns_hash[key].nil? %>
            <% key = key+"_id" %>
          <% end %>
          var element = document.getElementById("covid_situation_<%= key%>");
          element.classList.add("is-invalid");
          if ("<%= message[0] %>" != ""){
            var span = document.createElement('span');
            span.className = "invalid-feedback";
            span.append("<%= message[0] %>");
            element.parentElement.append(span);
          }
        <% end %>
      }
    </script>
  <% end %>
  <div class="row">
    <div class="col-md-4 form-group">
      <%= form.label :locality_id, "Localidad" %>
      <%= form.collection_select :locality_id, current_user.localities, :id, :to_s, {prompt: "Seleccionar localidad"}, {class: "select2 select-field form-control"} %>

    </div>

    <div class="form-group col-md-4">
      <%= form.label :part_date %>
      <%= form.text_field :part_date, hide_label:true, :class => "datepicker form-control"%>
    </div>

    
    <div class="col-md-12 title-form">
      <hr>
      <p class="form-title"><strong>Casos Nuevos</strong></p>
    </div>

    <div class="col-md-4 form-group">
      <%= form.label :new_cases %>
      <%= form.number_field :new_cases, class: "numeric-only active-field" %>
      <p class="font-italic font-weight-bold">Acumulado: <span id="new_cases_acumulated">0</span></p>
    </div>

    <div class="col-md-4 form-group">
      <%= form.label :new_recovered %>
      <%= form.number_field :new_recovered, class: "numeric-only active-field" %>
      <p class="font-italic font-weight-bold">Acumulado: <span id="new_recovered_acumulated">0</span></p>
    </div>

    <div class="col-md-4 form-group">
      <%= form.label :new_deceased %>
      <%= form.number_field :new_deceased, class: "numeric-only active-field" %>
      <p class="font-italic font-weight-bold">Acumulado: <span id="new_deceased_acumulated">0</span></p>
    </div>

    <div class="col-md-12 title-form">
      <p class="form-title"><strong>Actualización de Activos</strong></p>
    </div>


    <div class="col-md-3 form-group">
      <%= form.label :ambulatory %>
      <%= form.number_field :ambulatory, class: "numeric-only active-field" %>
    </div>

    <div class="col-md-3 form-group">
      <%= form.label :general_room %>
      <%= form.number_field :general_room, class: "numeric-only active-field" %>
    </div>

    <div class="col-md-3 form-group">
      <%= form.label :uti_without_arm %>
      <%= form.number_field :uti_without_arm, class: "numeric-only active-field" %>
    </div>
    
    <div class="col-md-3 form-group">
      <%= form.label :uti_with_arm %>
      <%= form.number_field :uti_with_arm, class: "numeric-only active-field" %>
    </div>

    <div class="col-md-12">
      <span id="autocomplete-activo" href="#" class="btn btn-secondary">Autocompletar</span>
      <span id="clean-activo" href="#" class="btn btn-secondary">Limpiar</span>
    </div>
    
    <div class="col-md-12 actions">
      <hr>
      <%= form.submit :class => "btn btn-success" %>
      <a class="btn btn-secondary" href="/">Volver al inicio</a>
    </div>
  </div>
<% end %>


<script type="text/javascript">

  
  $('.numeric-only').ForceNumericOnly();
  $('#autocomplete-activo').click(function() {
    if (!$('#covid_situation_new_cases').val())
      $('#covid_situation_new_cases').val(0);
    if (!$('#covid_situation_new_recovered').val())
      $('#covid_situation_new_recovered').val(0);
    if (!$('#covid_situation_new_deceased').val())
      $('#covid_situation_new_deceased').val(0);
    if (!$('#covid_situation_ambulatory').val())
      $('#covid_situation_ambulatory').val(0);
    if (!$('#covid_situation_general_room').val())
      $('#covid_situation_general_room').val(0);
    if (!$('#covid_situation_uti_with_arm').val())
      $('#covid_situation_uti_with_arm').val(0);
    if (!$('#covid_situation_uti_without_arm').val())
      $('#covid_situation_uti_without_arm').val(0);
    update_acumulated_to_all_type_cases();
  });

  $('#clean-activo').click(function() {
    $('.active-field').val("");
    update_acumulated_to_all_type_cases();
  });


  function update_acumulated (case_type, value) {
    locality_id = $("#covid_situation_locality_id").val();
    part_date = $("#covid_situation_part_date").val();
    if (locality_id != '' && part_date != '') {
      console.log("Actualizar acumulado de " + case_type);
      $.ajax({
        url: "/get_acumulated/"+locality_id+"/"+part_date+"/"+case_type+"/"+value,
        type: 'POST'
      }).done(function(data) {
        console.log (data)
        switch(data.case_type) {
          case "new_cases":
            $("#new_cases_acumulated").text(data.value);
            break;
          case "new_recovered":
            $("#new_recovered_acumulated").text(data.value);
            break;
          case "new_deceased":
            $("#new_deceased_acumulated").text(data.value);
            break;
          default:
            console.log("Default");
        } 
      });
    }
  }

  function update_acumulated_to_all_type_cases () {
    new_cases_value = $("#covid_situation_new_cases").val()
    if (new_cases_value != '')
      update_acumulated ("new_cases", $("#covid_situation_new_cases").val());
    else
      update_acumulated ("new_cases", 0);


    new_recovered_value = $("#covid_situation_new_recovered").val()
    if (new_recovered_value != '')
      update_acumulated ("new_recovered", $("#covid_situation_new_recovered").val());
    else
      update_acumulated ("new_recovered", 0);
    
    new_deceased_value = $("#covid_situation_new_deceased").val()
    if (new_deceased_value != '')
      update_acumulated ("new_deceased", $("#covid_situation_new_deceased").val());
    else
      update_acumulated ("new_deceased", 0);


  }

  $(document).ready(function(){
    if (($('.covid_situations.new').length + $('.covid_situations.create').length ) > 0) {
      $("#covid_situation_locality_id").on("change", function() {
        console.log ("Cambio la Localidad a " + this.value);
        update_acumulated_to_all_type_cases ();
      });

      $("#covid_situation_part_date").on('change', function() {
        console.log ("Cambio la fecha a " + this.value);
        update_acumulated_to_all_type_cases ();
      });

      $("#covid_situation_new_cases").keyup(function() {
        if (event.key >= 0 && event.key <= 9)
          update_acumulated ("new_cases", this.value);
      });

      $("#covid_situation_new_recovered").keyup(function() {
        if (event.key >= 0 && event.key <= 9)
          update_acumulated ("new_recovered", this.value);
      });

      $("#covid_situation_new_deceased").keyup(function() {
        if (event.key >= 0 && event.key <= 9)
          update_acumulated ("new_deceased", this.value);
      });
    }
  });  

</script>

app/views/covid_situations/edit.html.erb
<section id="formulario" class="formulario-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2 justify-content-center">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <h2 class="text-center">Editar Parte Diario</h2>
              <%= render 'form', covid_situation: @covid_situation %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/covid_situations/index.html.erb
<div class="container">
  <h2 class="pt-2">Datos covid por Localidad</h2>

  <table class="responsive nowrap table table-hover table-bordered" id="dttb-covid_situations" data-sort="true" data-source="<%= url_for(format: :json)%>">
    <thead>
      <tr>
        <th rowspan="2" data-data="locality">Localidad</th>
        <th rowspan="2" data-data="part_date">Fecha</th>
        <th colspan="3" style="color:green;">Casos Nuevos</th>
        <th colspan="3" style="color:darkblue;">Casos Acumulados</th>
        <th rowspan="2" data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px">Opciones</th>
      </tr>
      <tr>
        <th data-data="new_cases" style="color:green;">Confirmados</th>
        <th data-data="new_recovered" style="color:green;">Recuperados</th>
        <th data-data="new_deceased" style="color:green;">Fallecidos</th>
        <th data-data="acumulated_new" style="color:darkblue;">Confirmados</th>
        <th data-data="acumulated_recovered" style="color:darkblue;">Recuperados</th>
        <th data-data="acumulated_deceased" style="color:darkblue;">Fallecidos</th>
      </tr>
    </thead>

  </table>

  <br>

  <%= link_to 'Nueva Situación', new_covid_situation_path, class: "btn btn-primary" %>

  </div>

app/views/covid_situations/new.html.erb
<section id="formulario" class="formulario-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2 justify-content-center">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <h2 class="text-center">Cargar Nuevo Parte Diario</h2>
              <%= render 'form', covid_situation: @covid_situation %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/covid_situations/show.html.erb
<section id="felicitaciones" class="felicitaciones-section py-5">
  <div class="container">
    <div class="panel-pane pane-texto">
      <div class="pane-content">
        <div class="">
          <div class="row my-2">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="row justify-content-center">
                <div class="col-md-12 text-left">
                  <strong>Locality:</strong>
                  <%= @covid_situation.locality %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Fecha del Parte:</strong>
                  <%= @covid_situation.part_date %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Nuevos Casos:</strong>
                  <%= @covid_situation.new_cases %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Nuevos Acumulado:</strong>
                  <%= @covid_situation.acumulated_new %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Nuevos Recuperados:</strong>
                  <%= @covid_situation.new_recovered %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Ambulatory:</strong>
                  <%= @covid_situation.ambulatory %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>General room:</strong>
                  <%= @covid_situation.general_room %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Uti with arm:</strong>
                  <%= @covid_situation.uti_with_arm %>
                </div>

                <div class="col-md-12 text-left">
                  <strong>Uti without arm:</strong>
                  <%= @covid_situation.uti_without_arm %>
                </div>

                

                <%= link_to 'Edit', edit_covid_situation_path(@covid_situation) %> |
                <%= link_to 'Back', covid_situations_path %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>