config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_schemes
  
  resources :notices
  
  resources :covid_situations
  
  resources :covid_current
  post 'covid_current/part_locality' => 'covid_current#part_locality', :as => :part_locality
  
  #resources :covid_cases
  #get 'covid_cases/:id/confirm' => 'covid_cases#confirm', :as => :confirm_covid_case
  #get 'covid_cases/:id/pdf_confirm' => 'covid_cases#pdf_confirm', :as => :pdf_confirm_covid_case
  #get 'covid_cases/:id/pdf_suspicious' => 'covid_cases#pdf_suspicious', :as => :pdf_suspicious_covid_case
  #get 'covid_cases/:id/pdf_contact' => 'covid_cases#pdf_contact', :as => :pdf_contact_covid_case
  

  resources :localities
  resources :states
  resources :areas

  post '/get_acumulated/:locality_id/:part_date/:case_type/:new_value' => 'covid_situations#get_acumulated'

  devise_for :users
  root 'welcome#index'


end

app/models/state.rb
class State < ApplicationRecord
    has_many :covid_cases

    def to_s
        name
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_state, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  
  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>States</h1>

<table class="responsive nowrap table table-hover" id="dttb-states" data-sort="true" data-source="<%= url_for(format: :json)%>">
  <thead>
    <tr>
      <th data-data="name">Name</th>
      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
    </tr>
  </thead>

</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>